### ISSUE TITLE
Must add validation to external dependencies

### ISSUE THREAD

**Issue by girikuncoro** [mahakamcloud/mahakam#22]
When starting mahakam, must do precheck on all configuration and external dependencies: i.e. check whether kvstore is accessible or not.

**Comment by himani93** [comment]
External components to verify connectivity for:

- [ ] KVStore
- [ ] Baremetal Hosts passed in Config

**Comment by vjdhama** [comment]
Decided to skip baremetal host check before starting server. This would make server startup very slow. We will have to rethink the approach to doing that post server startup.

Fixed in https://github.com/mahakamcloud/mahakam/commit/4cda470a3c9471856c369939d82356e8650b2b8c
